// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9QZz5UBoYxNjp-jvmuFMb1JfXmESY3k',
    appId: '1:85253185174:web:8000910671ff97e65d2cb7',
    messagingSenderId: '85253185174',
    projectId: 'sir-park-allot',
    authDomain: 'sir-park-allot.firebaseapp.com',
    storageBucket: 'sir-park-allot.appspot.com',
    measurementId: 'G-ZN8MH32XVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0QiuAVYJEJ9gUXIL52qpQF5U_BCSFeIQ',
    appId: '1:85253185174:android:21dbcf63902529895d2cb7',
    messagingSenderId: '85253185174',
    projectId: 'sir-park-allot',
    storageBucket: 'sir-park-allot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2UoQad5AtrfldZ8-VTpd5_Liaxf_603g',
    appId: '1:85253185174:ios:24d49a6884e147825d2cb7',
    messagingSenderId: '85253185174',
    projectId: 'sir-park-allot',
    storageBucket: 'sir-park-allot.appspot.com',
    iosClientId: '85253185174-p3r6jcudknq5htng3ee49ip07d9i34ub.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2UoQad5AtrfldZ8-VTpd5_Liaxf_603g',
    appId: '1:85253185174:ios:de2bb49c6943c0bc5d2cb7',
    messagingSenderId: '85253185174',
    projectId: 'sir-park-allot',
    storageBucket: 'sir-park-allot.appspot.com',
    iosClientId: '85253185174-s2hp0eo6rm3uvecnv36iaou5bpu9kje9.apps.googleusercontent.com',
    iosBundleId: 'com.example.userApp.RunnerTests',
  );
}
